[versions]
minSdk = "21"
compileSdk = "35"
targetSdk = "35"

androidgradleplugin = "8.13.2"
kotlin = "2.3.0"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
material = { module = "com.google.android.material:material", version = "1.13.0" }
plugin-android-cache-fix = { module = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin", version = "3.0.3" }
plugin-androidgradleplugin = { module = "com.android.tools.build:gradle", version.ref = "androidgradleplugin" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version = "1.14.1" }
plugin-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.35.0" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "2.1.0" }

[plugins]
codequalitytools = { id = "com.vanniktech.code.quality.tools", version = "0.25.0" }
